# Generated by Django 4.1.1 on 2022-09-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DateofJoining',
            field=models.DateField(verbose_name='mm/dd/yyyy'),
        ),
    ]
